import type { Metadata } from "next";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Content from "../components/Content";
import "@/app/globals.css";
import ThemeScript from "../components/provider/ThemeScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className="max-auto max-w-3xl px-6 lg:max-w-6xl lg:px-8 font-sans">
        <Header />
        <Content>{children}</Content>
        <Footer />
      </body>
    </html>
  );
}
